lsp: 2020-05-15 21:30:58 UTC pid: 32408 - MainThread - EXCEPTION - robotframework_ls.server_api.server
Error collecting errors.

Traceback (most recent call last):
  File "c:\users\skadiyala\appdata\local\programs\python\python38-32\lib\site-packages\robotframework_ls\server_api\server.py", line 85, in m_lint
    errors.extend(code_analysis.collect_analysis_errors(completion_context))
  File "c:\users\skadiyala\appdata\local\programs\python\python38-32\lib\site-packages\robotframework_ls\impl\code_analysis.py", line 107, in collect_analysis_errors
    collect_keywords(completion_context, collector)
  File "c:\users\skadiyala\appdata\local\programs\python\python38-32\lib\site-packages\robotframework_ls\impl\collect_keywords.py", line 335, in collect_keywords
    _collect_following_imports(completion_context, collector)
  File "c:\users\skadiyala\appdata\local\programs\python\python38-32\lib\site-packages\robotframework_ls\impl\collect_keywords.py", line 273, in _collect_following_imports
    _collect_libraries_keywords(completion_context, collector)
  File "c:\users\skadiyala\appdata\local\programs\python\python38-32\lib\site-packages\robotframework_ls\impl\collect_keywords.py", line 231, in _collect_libraries_keywords
    library_doc = libspec_manager.get_library_info(
  File "c:\users\skadiyala\appdata\local\programs\python\python38-32\lib\site-packages\robotframework_ls\impl\libspec_manager.py", line 452, in get_library_info
    libname_lower = libname.lower()
AttributeError: 'NoneType' object has no attribute 'lower'
lsp: 2020-05-15 21:31:00 UTC pid: 32408 - MainThread - EXCEPTION - robotframework_ls.server_api.server
Error collecting errors.

Traceback (most recent call last):
  File "c:\users\skadiyala\appdata\local\programs\python\python38-32\lib\site-packages\robotframework_ls\server_api\server.py", line 85, in m_lint
    errors.extend(code_analysis.collect_analysis_errors(completion_context))
  File "c:\users\skadiyala\appdata\local\programs\python\python38-32\lib\site-packages\robotframework_ls\impl\code_analysis.py", line 107, in collect_analysis_errors
    collect_keywords(completion_context, collector)
  File "c:\users\skadiyala\appdata\local\programs\python\python38-32\lib\site-packages\robotframework_ls\impl\collect_keywords.py", line 335, in collect_keywords
    _collect_following_imports(completion_context, collector)
  File "c:\users\skadiyala\appdata\local\programs\python\python38-32\lib\site-packages\robotframework_ls\impl\collect_keywords.py", line 273, in _collect_following_imports
    _collect_libraries_keywords(completion_context, collector)
  File "c:\users\skadiyala\appdata\local\programs\python\python38-32\lib\site-packages\robotframework_ls\impl\collect_keywords.py", line 231, in _collect_libraries_keywords
    library_doc = libspec_manager.get_library_info(
  File "c:\users\skadiyala\appdata\local\programs\python\python38-32\lib\site-packages\robotframework_ls\impl\libspec_manager.py", line 452, in get_library_info
    libname_lower = libname.lower()
AttributeError: 'NoneType' object has no attribute 'lower'
lsp: 2020-05-15 21:31:02 UTC pid: 32408 - MainThread - EXCEPTION - robotframework_ls.server_api.server
Error collecting errors.

Traceback (most recent call last):
  File "c:\users\skadiyala\appdata\local\programs\python\python38-32\lib\site-packages\robotframework_ls\server_api\server.py", line 85, in m_lint
    errors.extend(code_analysis.collect_analysis_errors(completion_context))
  File "c:\users\skadiyala\appdata\local\programs\python\python38-32\lib\site-packages\robotframework_ls\impl\code_analysis.py", line 107, in collect_analysis_errors
    collect_keywords(completion_context, collector)
  File "c:\users\skadiyala\appdata\local\programs\python\python38-32\lib\site-packages\robotframework_ls\impl\collect_keywords.py", line 335, in collect_keywords
    _collect_following_imports(completion_context, collector)
  File "c:\users\skadiyala\appdata\local\programs\python\python38-32\lib\site-packages\robotframework_ls\impl\collect_keywords.py", line 273, in _collect_following_imports
    _collect_libraries_keywords(completion_context, collector)
  File "c:\users\skadiyala\appdata\local\programs\python\python38-32\lib\site-packages\robotframework_ls\impl\collect_keywords.py", line 231, in _collect_libraries_keywords
    library_doc = libspec_manager.get_library_info(
  File "c:\users\skadiyala\appdata\local\programs\python\python38-32\lib\site-packages\robotframework_ls\impl\libspec_manager.py", line 452, in get_library_info
    libname_lower = libname.lower()
AttributeError: 'NoneType' object has no attribute 'lower'
lsp: 2020-05-15 21:31:03 UTC pid: 32408 - MainThread - EXCEPTION - robotframework_ls.server_api.server
Error collecting errors.

Traceback (most recent call last):
  File "c:\users\skadiyala\appdata\local\programs\python\python38-32\lib\site-packages\robotframework_ls\server_api\server.py", line 85, in m_lint
    errors.extend(code_analysis.collect_analysis_errors(completion_context))
  File "c:\users\skadiyala\appdata\local\programs\python\python38-32\lib\site-packages\robotframework_ls\impl\code_analysis.py", line 107, in collect_analysis_errors
    collect_keywords(completion_context, collector)
  File "c:\users\skadiyala\appdata\local\programs\python\python38-32\lib\site-packages\robotframework_ls\impl\collect_keywords.py", line 335, in collect_keywords
    _collect_following_imports(completion_context, collector)
  File "c:\users\skadiyala\appdata\local\programs\python\python38-32\lib\site-packages\robotframework_ls\impl\collect_keywords.py", line 273, in _collect_following_imports
    _collect_libraries_keywords(completion_context, collector)
  File "c:\users\skadiyala\appdata\local\programs\python\python38-32\lib\site-packages\robotframework_ls\impl\collect_keywords.py", line 231, in _collect_libraries_keywords
    library_doc = libspec_manager.get_library_info(
  File "c:\users\skadiyala\appdata\local\programs\python\python38-32\lib\site-packages\robotframework_ls\impl\libspec_manager.py", line 452, in get_library_info
    libname_lower = libname.lower()
AttributeError: 'NoneType' object has no attribute 'lower'
lsp: 2020-05-15 21:31:05 UTC pid: 32408 - MainThread - EXCEPTION - robotframework_ls.impl.libspec_manager
Error creating libspec: Se. Output:
Importing test library 'Se' failed: ModuleNotFoundError: No module named 'Se'

Traceback (most recent call last):

  None

PYTHONPATH:

  c:\development\robot-scripts\MyProgram\Tests\SeleniumRobot

  c:\development\robot-scripts\MyProgram\Tests\SeleniumRobot

  c:\users\skadiyala\appdata\local\programs\python\python38-32\python38.zip

  c:\users\skadiyala\appdata\local\programs\python\python38-32\DLLs

  c:\users\skadiyala\appdata\local\programs\python\python38-32\lib

  c:\users\skadiyala\appdata\local\programs\python\python38-32

  C:\Users\skadiyala\AppData\Roaming\Python\Python38\site-packages

  c:\users\skadiyala\appdata\local\programs\python\python38-32\lib\site-packages

  c:\users\skadiyala\appdata\local\programs\python\python38-32\lib\site-packages\win32

  c:\users\skadiyala\appdata\local\programs\python\python38-32\lib\site-packages\win32\lib

  c:\users\skadiyala\appdata\local\programs\python\python38-32\lib\site-packages\Pythonwin



Try --help for usage information.



Traceback (most recent call last):
  File "c:\users\skadiyala\appdata\local\programs\python\python38-32\lib\site-packages\robotframework_ls\impl\libspec_manager.py", line 407, in _create_libspec
    subprocess.check_output(
  File "c:\users\skadiyala\appdata\local\programs\python\python38-32\lib\subprocess.py", line 411, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "c:\users\skadiyala\appdata\local\programs\python\python38-32\lib\subprocess.py", line 512, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['c:\\users\\skadiyala\\appdata\\local\\programs\\python\\python38-32\\python.exe', '-m', 'robot.libdoc', '--format', 'XML:HTML', '-P', 'c:\\development\\robot-scripts\\MyProgram\\Tests\\SeleniumRobot', 'Se', 'C:\\Users\\skadiyala\\robotframework_ls\\libspec\\d1b65505_3.2.1\\user\\Se.libspec']' returned non-zero exit status 252.
lsp: 2020-05-15 21:31:06 UTC pid: 32408 - MainThread - EXCEPTION - robotframework_ls.impl.libspec_manager
Error creating libspec: Seleniu. Output:
Importing test library 'Seleniu' failed: ModuleNotFoundError: No module named 'Seleniu'

Traceback (most recent call last):

  None

PYTHONPATH:

  c:\development\robot-scripts\MyProgram\Tests\SeleniumRobot

  c:\development\robot-scripts\MyProgram\Tests\SeleniumRobot

  c:\users\skadiyala\appdata\local\programs\python\python38-32\python38.zip

  c:\users\skadiyala\appdata\local\programs\python\python38-32\DLLs

  c:\users\skadiyala\appdata\local\programs\python\python38-32\lib

  c:\users\skadiyala\appdata\local\programs\python\python38-32

  C:\Users\skadiyala\AppData\Roaming\Python\Python38\site-packages

  c:\users\skadiyala\appdata\local\programs\python\python38-32\lib\site-packages

  c:\users\skadiyala\appdata\local\programs\python\python38-32\lib\site-packages\win32

  c:\users\skadiyala\appdata\local\programs\python\python38-32\lib\site-packages\win32\lib

  c:\users\skadiyala\appdata\local\programs\python\python38-32\lib\site-packages\Pythonwin



Try --help for usage information.



Traceback (most recent call last):
  File "c:\users\skadiyala\appdata\local\programs\python\python38-32\lib\site-packages\robotframework_ls\impl\libspec_manager.py", line 407, in _create_libspec
    subprocess.check_output(
  File "c:\users\skadiyala\appdata\local\programs\python\python38-32\lib\subprocess.py", line 411, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "c:\users\skadiyala\appdata\local\programs\python\python38-32\lib\subprocess.py", line 512, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['c:\\users\\skadiyala\\appdata\\local\\programs\\python\\python38-32\\python.exe', '-m', 'robot.libdoc', '--format', 'XML:HTML', '-P', 'c:\\development\\robot-scripts\\MyProgram\\Tests\\SeleniumRobot', 'Seleniu', 'C:\\Users\\skadiyala\\robotframework_ls\\libspec\\d1b65505_3.2.1\\user\\Seleniu.libspec']' returned non-zero exit status 252.
lsp: 2020-05-15 22:08:59 UTC pid: 32408 - MainThread - EXCEPTION - robotframework_ls.jsonrpc.endpoint
Failed to handle request 718

Traceback (most recent call last):
  File "c:\users\skadiyala\appdata\local\programs\python\python38-32\lib\site-packages\robotframework_ls\jsonrpc\endpoint.py", line 143, in consume
    self._handle_request(
  File "c:\users\skadiyala\appdata\local\programs\python\python38-32\lib\site-packages\robotframework_ls\jsonrpc\endpoint.py", line 228, in _handle_request
    handler_result = handler(params)
  File "c:\users\skadiyala\appdata\local\programs\python\python38-32\lib\site-packages\robotframework_ls\jsonrpc\dispatchers.py", line 38, in handler
    return method(**(params or {}))
  File "c:\users\skadiyala\appdata\local\programs\python\python38-32\lib\site-packages\robotframework_ls\server_api\server.py", line 131, in m_find_definition
    definitions = find_definition(completion_context)
  File "c:\users\skadiyala\appdata\local\programs\python\python38-32\lib\site-packages\robotframework_ls\impl\find_definition.py", line 85, in find_definition
    return collector.matches
UnboundLocalError: local variable 'collector' referenced before assignment
lsp: 2020-05-16 00:34:19 UTC pid: 32408 - MainThread - EXCEPTION - robotframework_ls.server_api.server
Error collecting errors.

Traceback (most recent call last):
  File "c:\users\skadiyala\appdata\local\programs\python\python38-32\lib\site-packages\robotframework_ls\server_api\server.py", line 85, in m_lint
    errors.extend(code_analysis.collect_analysis_errors(completion_context))
  File "c:\users\skadiyala\appdata\local\programs\python\python38-32\lib\site-packages\robotframework_ls\impl\code_analysis.py", line 110, in collect_analysis_errors
    for keyword_usage_info in ast_utils.iter_keyword_usage_tokens(ast):
  File "c:\users\skadiyala\appdata\local\programs\python\python38-32\lib\site-packages\robotframework_ls\impl\ast_utils.py", line 369, in iter_keyword_usage_tokens
    token = _strip_token_bdd_prefix(node.get_token(Token.KEYWORD))
  File "c:\users\skadiyala\appdata\local\programs\python\python38-32\lib\site-packages\robotframework_ls\impl\ast_utils.py", line 433, in _strip_token_bdd_prefix
    text = normalize_robot_name(token.value)
AttributeError: 'NoneType' object has no attribute 'value'
lsp: 2020-05-16 00:34:21 UTC pid: 32408 - MainThread - EXCEPTION - robotframework_ls.server_api.server
Error collecting errors.

Traceback (most recent call last):
  File "c:\users\skadiyala\appdata\local\programs\python\python38-32\lib\site-packages\robotframework_ls\server_api\server.py", line 85, in m_lint
    errors.extend(code_analysis.collect_analysis_errors(completion_context))
  File "c:\users\skadiyala\appdata\local\programs\python\python38-32\lib\site-packages\robotframework_ls\impl\code_analysis.py", line 110, in collect_analysis_errors
    for keyword_usage_info in ast_utils.iter_keyword_usage_tokens(ast):
  File "c:\users\skadiyala\appdata\local\programs\python\python38-32\lib\site-packages\robotframework_ls\impl\ast_utils.py", line 369, in iter_keyword_usage_tokens
    token = _strip_token_bdd_prefix(node.get_token(Token.KEYWORD))
  File "c:\users\skadiyala\appdata\local\programs\python\python38-32\lib\site-packages\robotframework_ls\impl\ast_utils.py", line 433, in _strip_token_bdd_prefix
    text = normalize_robot_name(token.value)
AttributeError: 'NoneType' object has no attribute 'value'
lsp: 2020-05-16 00:46:05 UTC pid: 32408 - MainThread - EXCEPTION - robotframework_ls.jsonrpc.endpoint
Failed to handle request 1762

Traceback (most recent call last):
  File "c:\users\skadiyala\appdata\local\programs\python\python38-32\lib\site-packages\robotframework_ls\jsonrpc\endpoint.py", line 143, in consume
    self._handle_request(
  File "c:\users\skadiyala\appdata\local\programs\python\python38-32\lib\site-packages\robotframework_ls\jsonrpc\endpoint.py", line 228, in _handle_request
    handler_result = handler(params)
  File "c:\users\skadiyala\appdata\local\programs\python\python38-32\lib\site-packages\robotframework_ls\jsonrpc\dispatchers.py", line 38, in handler
    return method(**(params or {}))
  File "c:\users\skadiyala\appdata\local\programs\python\python38-32\lib\site-packages\robotframework_ls\server_api\server.py", line 131, in m_find_definition
    definitions = find_definition(completion_context)
  File "c:\users\skadiyala\appdata\local\programs\python\python38-32\lib\site-packages\robotframework_ls\impl\find_definition.py", line 85, in find_definition
    return collector.matches
UnboundLocalError: local variable 'collector' referenced before assignment
lsp: 2020-05-16 01:06:19 UTC pid: 32408 - MainThread - EXCEPTION - robotframework_ls.jsonrpc.endpoint
Failed to handle request 1948

Traceback (most recent call last):
  File "c:\users\skadiyala\appdata\local\programs\python\python38-32\lib\site-packages\robotframework_ls\jsonrpc\endpoint.py", line 143, in consume
    self._handle_request(
  File "c:\users\skadiyala\appdata\local\programs\python\python38-32\lib\site-packages\robotframework_ls\jsonrpc\endpoint.py", line 228, in _handle_request
    handler_result = handler(params)
  File "c:\users\skadiyala\appdata\local\programs\python\python38-32\lib\site-packages\robotframework_ls\jsonrpc\dispatchers.py", line 38, in handler
    return method(**(params or {}))
  File "c:\users\skadiyala\appdata\local\programs\python\python38-32\lib\site-packages\robotframework_ls\server_api\server.py", line 131, in m_find_definition
    definitions = find_definition(completion_context)
